# Generated by Django 2.0.5 on 2018-05-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='registration',
            field=models.IntegerField(verbose_name='Registration'),
        ),
    ]
