# Generated by Django 2.0.5 on 2018-05-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180528_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='registration',
            field=models.IntegerField(null=True, verbose_name='Registration'),
        ),
    ]
