# Generated by Django 2.0.5 on 2018-05-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=9)),
                ('year', models.PositiveSmallIntegerField()),
                ('plate', models.CharField(max_length=7)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
    ]
